version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend-image
    container_name: frontend-container
    ports:
      - "80:80"

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    volumes:
      - frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  frontend:
