version: '3'
services:
  trailapp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./path/to/your/app/code:/usr/src/app/TRAILAPP/Backend